source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj 'EFTools.xcodeproj'

pod 'ParseUI'
pod 'ParseFacebookUtils'
pod 'ParseTwitterUtils'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON', :branch => 'xcode7'
pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit', :branch => 'swift-2.0'
pod 'AFDateHelper', :git => 'https://github.com/melvitax/AFDateHelper', :branch => 'Swift2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Instabug'
pod 'TPKeyboardAvoiding'