source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj 'EFTools.xcodeproj'

pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'
pod 'Alamofire', '~>3.1'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'AFDateHelper'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Instabug'
pod 'TPKeyboardAvoiding'
pod 'SwiftKeychainWrapper'
pod 'SCLAlertView'